# Generated by Django 3.1.3 on 2020-11-18 08:57

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=10)),
                ('entry_date', models.DateField(default=django.utils.timezone.now)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('mobile_number', models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message='输入的电话号码格式不对', regex='^[0-9]{11,8}$')])),
                ('address', models.TextField(blank=True)),
            ],
        ),
    ]
